### GET request to example server
GET http://localhost:8080/

### GET list of all blogposts
GET http://localhost:8080/blogposts
Accept: application/json

### GET single blogpost by ID
GET http://localhost:8080/blogposts/27ce87a8-a7e0-4e2e-afe1-5b5c11012c11
Accept: application/json

### CREATE a blogpost
POST http://localhost:8080/blogposts
Accept: application/json
Content-Type: application/json

{
  "title": "New Blogpost Title",
  "text": "This is the content of the new blogpost.",
  "author": "New Author",
  "createdAt": "2023-10-27T10:00:00+01:00",
  "updatedAt": "2023-10-27T10:00:00+01:00"
}

### UPDATE a blogpost
PUT http://localhost:8080/blogposts/2305ecb7-5a13-42b4-9f97-ebe976adbd04
Accept: application/json
Content-Type: application/json

{
  "id": "27ce87a8-a7e0-4e2e-afe1-5b5c11012c11",
  "title": "Updated Blogpost Title",
  "text": "This is the updated content of the blogpost.",
  "author": "Updated Author",
  "createdAt": "2021-02-01T10:00:00+01:00",
  "updatedAt": "2023-10-27T11:30:00+01:00"
}

### DELETE a blogpost
DELETE http://localhost:8080/blogposts/2305ecb7-5a13-42b4-9f97-ebe976adbd04
