### GET request to example server
GET http://localhost:8080/

### GET list of all blogposts
GET http://localhost:8080/blogposts
Accept: application/json

### GET list of all blogposts by author
GET http://localhost:8080/blogposts?author=Author%201
Accept: application/json

### GET list of all blogposts by author
GET http://localhost:8080/blogposts?createdAt=2026-02-05
Accept: application/json

### GET list of all blogposts by author
GET http://localhost:8080/blogposts?author=Author%202&createdAt=2026-02-05
Accept: application/json


### GET single blogpost by ID
GET http://localhost:8080/blogposts/3ceed4e8-f8fd-4e2b-bf47-f43419b26156
Accept: application/json

### CREATE a blogpost
POST http://localhost:8080/blogposts
Accept: application/json
Content-Type: application/json

{
  "title": "My fancy title",
  "text": "This is the content of the new blogpost.",
  "author": "New Author"
}

### UPDATE a blogpost
PUT http://localhost:8080/blogposts/7312e653-c101-4bfc-a131-cf045bf7c9f8
Accept: application/json
Content-Type: application/json

{
  "title": "Updated Blogpost Title",
  "text": "This is the updated content of the blogpost.",
  "author": "Updated Author"
}

### DELETE a blogpost
DELETE http://localhost:8080/blogposts/2305ecb7-5a13-42b4-9f97-ebe976adbd04
